"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isSellAsVariants = exports.isSellAsSelf = exports.isSellAsMix = exports.isSellAsColors = exports.isCategoryChildProduct = exports.isCategoryChildSection = exports.isCategoryChildLink = exports.isCategoryChildCategory = exports.SELL_AS_SELF = exports.SELL_AS_MIX = exports.SELL_AS_COLORS = exports.SELL_AS_VARIANTS = exports.defaultVariant = exports.defaultProduct = exports.B2BError = void 0;
var b2b_error_1 = require("./b2b-error");
Object.defineProperty(exports, "B2BError", { enumerable: true, get: function () { return b2b_error_1.B2BError; } });
var product_constants_1 = require("./product-constants");
Object.defineProperty(exports, "defaultProduct", { enumerable: true, get: function () { return product_constants_1.defaultProduct; } });
Object.defineProperty(exports, "defaultVariant", { enumerable: true, get: function () { return product_constants_1.defaultVariant; } });
Object.defineProperty(exports, "SELL_AS_VARIANTS", { enumerable: true, get: function () { return product_constants_1.SELL_AS_VARIANTS; } });
Object.defineProperty(exports, "SELL_AS_COLORS", { enumerable: true, get: function () { return product_constants_1.SELL_AS_COLORS; } });
Object.defineProperty(exports, "SELL_AS_MIX", { enumerable: true, get: function () { return product_constants_1.SELL_AS_MIX; } });
Object.defineProperty(exports, "SELL_AS_SELF", { enumerable: true, get: function () { return product_constants_1.SELL_AS_SELF; } });
var product_utils_1 = require("./product-utils");
Object.defineProperty(exports, "isCategoryChildCategory", { enumerable: true, get: function () { return product_utils_1.isCategoryChildCategory; } });
Object.defineProperty(exports, "isCategoryChildLink", { enumerable: true, get: function () { return product_utils_1.isCategoryChildLink; } });
Object.defineProperty(exports, "isCategoryChildSection", { enumerable: true, get: function () { return product_utils_1.isCategoryChildSection; } });
Object.defineProperty(exports, "isCategoryChildProduct", { enumerable: true, get: function () { return product_utils_1.isCategoryChildProduct; } });
Object.defineProperty(exports, "isSellAsColors", { enumerable: true, get: function () { return product_utils_1.isSellAsColors; } });
Object.defineProperty(exports, "isSellAsMix", { enumerable: true, get: function () { return product_utils_1.isSellAsMix; } });
Object.defineProperty(exports, "isSellAsSelf", { enumerable: true, get: function () { return product_utils_1.isSellAsSelf; } });
Object.defineProperty(exports, "isSellAsVariants", { enumerable: true, get: function () { return product_utils_1.isSellAsVariants; } });
