import {Product} from "./products";

export const testProduct:Product =  {
    "id": 1073,
    "itemCode": "18403 Series",
    "keyword": "surfshorts-wallet-LTD",
    "name": "Surfshort LTD Wallet",
    "metaTitle": null,
    "description": "The Surfshort wallet is one of our best sellers. Its the perfect stash wallet and has a disappearing key ring. The LTD versions come in lots of cool patterns.\r\n",
    "details": "<ul> \r\n<li>Durable rip-stop nylon</li>\r\n<li>Two zip pockets for cards and cash</li>\r\n<li>All in one compact size fits small pockets</li>\r\n<li>Outside ID window</li> \r\n<li>Dimensions: 4.5\" x 3\"</li>\r\n</ul>",
    "image": "18403?.jpg",
    "status": true,
    "taxClassId": 0,
    "manufacturersId": 12,
    "materialsId": 0,
    "sellAs": 0,
    "upc": null,
    "defaultColor": "920",
    "defaultCategoriesId": 18,
    "defaultCategoryKeyword": "wallets",
    "defaultParentProductsId": 0,
    "options": "[]",
    "requireOptions": "[]",
    "canDome": false,
    "canScreenPrint": false,
    "availableForSale": true,
    "dateAvailable": "",
    "timestamp": "2022-01-24T19:21:35.000Z",
    "msrp": 0,
    "stdPrice": null,
    "priceCode": null,
    "stdUM": null,
    "salesUM": null,
    "salesUMFactor": null,
    "shipWeight": null,
    "productType": null,
    "QuantityAvailable": 0,
    "inactiveItem": false,
    "buffer": null,
    "redirectToParent": false,
    "parentProductKeyword": null,
    "additionalData": {
        "size": "",
        "subtitle": "",
        "formatted_name": "",
        "swatch_format": "?",
        "best_seller": true,
        "upcycled": null
    },
    "product_season_id": 0,
    "season_code": null,
    "season_description": null,
    "season_active": null,
    "season_available": false,
    "season_teaser": null,
    "anticipatedPrice": "0.0000",
    "variants": [
        {
            "id": 476,
            "parentProductID": 1073,
            "variantProductID": 1074,
            "title": "Singles",
            "isDefaultVariant": true,
            "status": true,
            "priority": 10,
            "timestamp": "2020-11-25T23:38:31.000Z",
            "product": {
                "id": 1074,
                "itemCode": "18403___",
                "keyword": "surfshorts-wallet-ltd-singles",
                "name": "Surfshort LTD Wallet Singles",
                "metaTitle": null,
                "description": "",
                "details": "",
                "image": "18403?.jpg",
                "status": true,
                "taxClassId": 0,
                "manufacturersId": 12,
                "materialsId": 0,
                "sellAs": 4,
                "upc": null,
                "defaultColor": "406",
                "defaultCategoriesId": 18,
                "defaultCategoryKeyword": "wallets",
                "defaultParentProductsId": 1073,
                "options": "[]",
                "requireOptions": "[]",
                "canDome": false,
                "canScreenPrint": false,
                "availableForSale": true,
                "dateAvailable": "",
                "timestamp": "2021-11-01T21:09:36.000Z",
                "msrp": 0,
                "stdPrice": null,
                "priceCode": null,
                "stdUM": null,
                "salesUM": null,
                "salesUMFactor": null,
                "shipWeight": null,
                "productType": null,
                "QuantityAvailable": 0,
                "inactiveItem": false,
                "buffer": null,
                "redirectToParent": true,
                "parentProductKeyword": "surfshorts-wallet-LTD",
                "additionalData": {
                    "size": "",
                    "subtitle": "",
                    "formatted_name": "",
                    "swatch_format": "?"
                },
                "product_season_id": 0,
                "season_code": null,
                "season_description": null,
                "season_active": null,
                "season_available": false,
                "season_teaser": null,
                "anticipatedPrice": "0.0000",
                "mix": null,
                "items": [
                    {
                        "id": 1948,
                        "productId": 1074,
                        "colorsId": 737,
                        "colorCode": "1014",
                        "itemCode": "184031014",
                        "colorName": "Western Black",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 544,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "",
                            "image_filename": "184031014_surfshort_LTD_western_front.jpg",
                            "season_id": 2,
                            "season": {
                                "product_season_id": 2,
                                "code": "SS22",
                                "description": "Available to ship in 2022",
                                "product_available": false,
                                "product_teaser": "New for 2022",
                                "active": true,
                                "properties": {
                                    "color": "#ffeb3b"
                                },
                                "timestamp": "2022-05-31T18:53:11.000Z"
                            }
                        },
                        "timestamp": "2021-11-01T20:55:01.000Z",
                        "color": {
                            "id": 737,
                            "code": "1014",
                            "name": "Western Black",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1945,
                        "productId": 1074,
                        "colorsId": 740,
                        "colorCode": "1020",
                        "itemCode": "184031020",
                        "colorName": "Western White",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 731,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "",
                            "image_filename": "184031020_surfshort_LTD_western_geo_front.jpg",
                            "season_id": 2,
                            "season": {
                                "product_season_id": 2,
                                "code": "SS22",
                                "description": "Available to ship in 2022",
                                "product_available": false,
                                "product_teaser": "New for 2022",
                                "active": true,
                                "properties": {
                                    "color": "#ffeb3b"
                                },
                                "timestamp": "2022-05-31T18:53:11.000Z"
                            }
                        },
                        "timestamp": "2021-11-01T20:56:21.000Z",
                        "color": {
                            "id": 740,
                            "code": "1020",
                            "name": "Western White",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1946,
                        "productId": 1074,
                        "colorsId": 742,
                        "colorCode": "1021",
                        "itemCode": "184031021",
                        "colorName": "Blue Permit Fish",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 1123,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "",
                            "image_filename": "184031021_surfshort_LTD_permit_front.jpg",
                            "season_id": 2,
                            "season": {
                                "product_season_id": 2,
                                "code": "SS22",
                                "description": "Available to ship in 2022",
                                "product_available": false,
                                "product_teaser": "New for 2022",
                                "active": true,
                                "properties": {
                                    "color": "#ffeb3b"
                                },
                                "timestamp": "2022-05-31T18:53:11.000Z"
                            }
                        },
                        "timestamp": "2021-11-01T20:57:43.000Z",
                        "color": {
                            "id": 742,
                            "code": "1021",
                            "name": "Blue Permit Fish",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1943,
                        "productId": 1074,
                        "colorsId": 741,
                        "colorCode": "1031",
                        "itemCode": "184031031",
                        "colorName": "Blue/Orange Bass Fish",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 1294,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "",
                            "image_filename": "184031031_surfshort_LTD_bass_front.jpg",
                            "season_id": 2,
                            "season": {
                                "product_season_id": 2,
                                "code": "SS22",
                                "description": "Available to ship in 2022",
                                "product_available": false,
                                "product_teaser": "New for 2022",
                                "active": true,
                                "properties": {
                                    "color": "#ffeb3b"
                                },
                                "timestamp": "2022-05-31T18:53:11.000Z"
                            }
                        },
                        "timestamp": "2021-11-01T20:59:33.000Z",
                        "color": {
                            "id": 741,
                            "code": "1031",
                            "name": "Blue/Orange Bass Fish",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1644,
                        "productId": 1074,
                        "colorsId": 673,
                        "colorCode": "196",
                        "itemCode": "18403196",
                        "colorName": "Jellyfish",
                        "status": false,
                        "msrp": 13.99,
                        "stdPrice": 6.5,
                        "priceCode": null,
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": -500,
                        "inactiveItem": 0,
                        "buffer": 500,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2019-07-11T15:00:19.000Z",
                        "color": {
                            "id": 673,
                            "code": "196",
                            "name": "Jellyfish",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1645,
                        "productId": 1074,
                        "colorsId": 674,
                        "colorCode": "197",
                        "itemCode": "18403197",
                        "colorName": "Redfish",
                        "status": false,
                        "msrp": 13.99,
                        "stdPrice": 6.5,
                        "priceCode": null,
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 0,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2019-07-11T15:00:25.000Z",
                        "color": {
                            "id": 674,
                            "code": "197",
                            "name": "Redfish",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1646,
                        "productId": 1074,
                        "colorsId": 675,
                        "colorCode": "198",
                        "itemCode": "18403198",
                        "colorName": "Green Dorado",
                        "status": false,
                        "msrp": 13.99,
                        "stdPrice": 6.5,
                        "priceCode": null,
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 0,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2019-07-11T15:00:29.000Z",
                        "color": {
                            "id": 675,
                            "code": "198",
                            "name": "Green Dorado",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1805,
                        "productId": 1074,
                        "colorsId": 682,
                        "colorCode": "351",
                        "itemCode": "18403351",
                        "colorName": "RealTree Edge",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "LSSR",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 455,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039849801",
                        "additionalData": {},
                        "timestamp": "2020-01-22T20:30:24.000Z",
                        "color": {
                            "id": 682,
                            "code": "351",
                            "name": "RealTree Edge",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1806,
                        "productId": 1074,
                        "colorsId": 703,
                        "colorCode": "352",
                        "itemCode": "18403352",
                        "colorName": "Realtree Wave",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "LSSR",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 550,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039849993",
                        "additionalData": {},
                        "timestamp": "2020-01-22T20:31:12.000Z",
                        "color": {
                            "id": 703,
                            "code": "352",
                            "name": "Realtree Wave",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1944,
                        "productId": 1074,
                        "colorsId": 139,
                        "colorCode": "406",
                        "itemCode": "18403406",
                        "colorName": "Camo Green",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 1412,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "",
                            "image_filename": "18403406_surfshort_LTD_fishing_division_front.jpg",
                            "season_id": 2,
                            "season": {
                                "product_season_id": 2,
                                "code": "SS22",
                                "description": "Available to ship in 2022",
                                "product_available": false,
                                "product_teaser": "New for 2022",
                                "active": true,
                                "properties": {
                                    "color": "#ffeb3b"
                                },
                                "timestamp": "2022-05-31T18:53:11.000Z"
                            }
                        },
                        "timestamp": "2021-11-01T21:00:40.000Z",
                        "color": {
                            "id": 139,
                            "code": "406",
                            "name": "Camo Green",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1947,
                        "productId": 1074,
                        "colorsId": 168,
                        "colorCode": "450",
                        "itemCode": "18403450",
                        "colorName": "Blue / Orange Stripe",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 193,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "",
                            "image_filename": "18403450_surfshort_LTD_stripes_front.jpg",
                            "season_id": 2,
                            "season": {
                                "product_season_id": 2,
                                "code": "SS22",
                                "description": "Available to ship in 2022",
                                "product_available": false,
                                "product_teaser": "New for 2022",
                                "active": true,
                                "properties": {
                                    "color": "#ffeb3b"
                                },
                                "timestamp": "2022-05-31T18:53:11.000Z"
                            }
                        },
                        "timestamp": "2021-11-01T21:01:42.000Z",
                        "color": {
                            "id": 168,
                            "code": "450",
                            "name": "Blue / Orange Stripe",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1888,
                        "productId": 1074,
                        "colorsId": 200,
                        "colorCode": "701",
                        "itemCode": "18403701",
                        "colorName": "Rainbow Tie-Dye",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 4376,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "ltd-701",
                            "image_filename": "18403701-surfshort-tiedye-front.jpg",
                            "season_id": 1,
                            "season": {
                                "product_season_id": 1,
                                "code": "SS21",
                                "description": "Available to ship spring 2021",
                                "product_available": true,
                                "product_teaser": "New for Spring 2021",
                                "active": true,
                                "properties": {
                                    "color": "#9c27b0"
                                },
                                "timestamp": "2022-05-31T18:53:11.000Z"
                            }
                        },
                        "timestamp": "2020-11-25T23:34:29.000Z",
                        "color": {
                            "id": 200,
                            "code": "701",
                            "name": "Rainbow Tie-Dye",
                            "swatchCode": "ltd-701"
                        }
                    },
                    {
                        "id": 1889,
                        "productId": 1074,
                        "colorsId": 205,
                        "colorCode": "707",
                        "itemCode": "18403707",
                        "colorName": "Red/White/Blue Tie-Dye",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 2664,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "ltd-707",
                            "image_filename": "18403707-surfshort-tiedye-front.jpg",
                            "season_id": 1,
                            "season": {
                                "product_season_id": 1,
                                "code": "SS21",
                                "description": "Available to ship spring 2021",
                                "product_available": true,
                                "product_teaser": "New for Spring 2021",
                                "active": true,
                                "properties": {
                                    "color": "#9c27b0"
                                },
                                "timestamp": "2022-05-31T18:53:11.000Z"
                            }
                        },
                        "timestamp": "2020-11-25T23:35:01.000Z",
                        "color": {
                            "id": 205,
                            "code": "707",
                            "name": "Red/White/Blue Tie-Dye",
                            "swatchCode": "ltd-707"
                        }
                    },
                    {
                        "id": 1648,
                        "productId": 1074,
                        "colorsId": 528,
                        "colorCode": "809",
                        "itemCode": "18403809",
                        "colorName": "American Flag",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 3564,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2019-03-19T19:55:16.000Z",
                        "color": {
                            "id": 528,
                            "code": "809",
                            "name": "American Flag",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1649,
                        "productId": 1074,
                        "colorsId": 584,
                        "colorCode": "872",
                        "itemCode": "18403872",
                        "colorName": "Colorado Flag",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 6,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "",
                            "image_filename": ""
                        },
                        "timestamp": "2020-06-04T19:06:06.000Z",
                        "color": {
                            "id": 584,
                            "code": "872",
                            "name": "Colorado Flag",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1650,
                        "productId": 1074,
                        "colorsId": 676,
                        "colorCode": "909",
                        "itemCode": "18403909",
                        "colorName": "BSA Tartan",
                        "status": false,
                        "msrp": 11.99,
                        "stdPrice": 5.5,
                        "priceCode": null,
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "D",
                        "QuantityAvailable": 0,
                        "inactiveItem": 1,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2019-07-11T15:00:38.000Z",
                        "color": {
                            "id": 676,
                            "code": "909",
                            "name": "BSA Tartan",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1890,
                        "productId": 1074,
                        "colorsId": 726,
                        "colorCode": "911",
                        "itemCode": "18403911",
                        "colorName": "High Vis Pink/Purple",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 1985,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {
                            "swatch_code": "ltd-911",
                            "image_filename": "18403911-surfshort-tiedye-front.jpg",
                            "season_id": 1,
                            "season": {
                                "product_season_id": 1,
                                "code": "SS21",
                                "description": "Available to ship spring 2021",
                                "product_available": true,
                                "product_teaser": "New for Spring 2021",
                                "active": true,
                                "properties": {
                                    "color": "#9c27b0"
                                },
                                "timestamp": "2022-05-31T18:53:11.000Z"
                            }
                        },
                        "timestamp": "2020-11-25T23:41:03.000Z",
                        "color": {
                            "id": 726,
                            "code": "911",
                            "name": "High Vis Pink/Purple",
                            "swatchCode": "ltd-911"
                        }
                    },
                    {
                        "id": 1807,
                        "productId": 1074,
                        "colorsId": 704,
                        "colorCode": "920",
                        "itemCode": "18403920",
                        "colorName": "Brook Fish",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 0,
                        "inactiveItem": 1,
                        "buffer": 604,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2020-01-22T20:31:28.000Z",
                        "color": {
                            "id": 704,
                            "code": "920",
                            "name": "Brook Fish",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1808,
                        "productId": 1074,
                        "colorsId": 705,
                        "colorCode": "921",
                        "itemCode": "18403921",
                        "colorName": "Rainbow Fish",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 0,
                        "inactiveItem": 1,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2020-01-22T20:31:32.000Z",
                        "color": {
                            "id": 705,
                            "code": "921",
                            "name": "Rainbow Fish",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1809,
                        "productId": 1074,
                        "colorsId": 706,
                        "colorCode": "922",
                        "itemCode": "18403922",
                        "colorName": "Dark Scales",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 0,
                        "inactiveItem": 1,
                        "buffer": 666,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2020-01-22T20:31:37.000Z",
                        "color": {
                            "id": 706,
                            "code": "922",
                            "name": "Dark Scales",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1810,
                        "productId": 1074,
                        "colorsId": 710,
                        "colorCode": "940",
                        "itemCode": "18403940",
                        "colorName": "Flamingos",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 562,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2020-01-22T20:31:45.000Z",
                        "color": {
                            "id": 710,
                            "code": "940",
                            "name": "Flamingos",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1811,
                        "productId": 1074,
                        "colorsId": 711,
                        "colorCode": "941",
                        "itemCode": "18403941",
                        "colorName": "Toucans",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 997,
                        "inactiveItem": 0,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2020-01-22T20:31:49.000Z",
                        "color": {
                            "id": 711,
                            "code": "941",
                            "name": "Toucans",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1812,
                        "productId": 1074,
                        "colorsId": 712,
                        "colorCode": "942",
                        "itemCode": "18403942",
                        "colorName": "Hawaiian Floral",
                        "status": true,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "F",
                        "QuantityAvailable": 526,
                        "inactiveItem": 0,
                        "buffer": 25,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2020-01-22T20:31:53.000Z",
                        "color": {
                            "id": 712,
                            "code": "942",
                            "name": "Hawaiian Floral",
                            "swatchCode": null
                        }
                    },
                    {
                        "id": 1652,
                        "productId": 1074,
                        "colorsId": 678,
                        "colorCode": "951",
                        "itemCode": "18403951",
                        "colorName": "EarlFish",
                        "status": false,
                        "msrp": 13.99,
                        "stdPrice": 7,
                        "priceCode": "PSW",
                        "stdUM": "EA",
                        "salesUM": "EA",
                        "salesUMFactor": 1,
                        "shipWeight": "0.0683",
                        "productType": "D",
                        "QuantityAvailable": 0,
                        "inactiveItem": 1,
                        "buffer": null,
                        "upc": "093039184032",
                        "additionalData": {},
                        "timestamp": "2020-02-20T18:29:34.000Z",
                        "color": {
                            "id": 678,
                            "code": "951",
                            "name": "EarlFish",
                            "swatchCode": null
                        }
                    }
                ],
                "images": []
            }
        },
        {
            "id": 512,
            "parentProductID": 1073,
            "variantProductID": 1118,
            "title": "Hawaiian Mix",
            "isDefaultVariant": false,
            "status": true,
            "priority": 20,
            "timestamp": "2020-11-25T23:38:21.000Z",
            "product": {
                "id": 1118,
                "itemCode": "1840347",
                "keyword": "surfshorts-ltd-hawaiian-mix",
                "name": "Surfshort LTD Hawaiian MIX",
                "metaTitle": "",
                "description": "",
                "details": "",
                "image": "18403?.jpg",
                "status": true,
                "taxClassId": 1,
                "manufacturersId": 12,
                "materialsId": 40,
                "sellAs": 3,
                "upc": "093039184032",
                "defaultColor": "940",
                "defaultCategoriesId": 18,
                "defaultCategoryKeyword": "wallets",
                "defaultParentProductsId": 1073,
                "options": "[]",
                "requireOptions": "[]",
                "canDome": false,
                "canScreenPrint": false,
                "availableForSale": true,
                "dateAvailable": "",
                "timestamp": "2020-01-22T20:39:20.000Z",
                "msrp": 13.99,
                "stdPrice": 7,
                "priceCode": "PSW",
                "stdUM": "EA",
                "salesUM": "6PK",
                "salesUMFactor": 6,
                "shipWeight": "0.0683",
                "productType": "F",
                "QuantityAvailable": 300,
                "inactiveItem": false,
                "buffer": null,
                "redirectToParent": true,
                "parentProductKeyword": "surfshorts-wallet-LTD",
                "additionalData": {
                    "size": "",
                    "subtitle": "",
                    "formatted_name": "",
                    "swatch_format": ""
                },
                "product_season_id": null,
                "season_code": null,
                "season_description": null,
                "season_active": null,
                "season_available": false,
                "season_teaser": null,
                "anticipatedPrice": "0.0000",
                "mix": {
                    "id": 226,
                    "productId": 1118,
                    "itemCode": "1840347",
                    "mixName": "Surfshort LTD Hawaiian MIX",
                    "status": true,
                    "msrp": 13.99,
                    "stdPrice": 7,
                    "priceCode": "PSW",
                    "stdUM": "EA",
                    "salesUM": "6PK",
                    "salesUMFactor": 6,
                    "shipWeight": "0.0683",
                    "productType": "F",
                    "QuantityAvailable": 300,
                    "inactiveItem": 0,
                    "buffer": null,
                    "timestamp": "2020-01-22T20:36:25.000Z",
                    "items": [
                        {
                            "id": 1396,
                            "mixID": 226,
                            "itemCode": "18403940",
                            "itemQuantity": 2,
                            "colorsId": 710,
                            "color_code": "940",
                            "color_name": "Flamingos",
                            "additionalData": {},
                            "color": {
                                "id": 710,
                                "code": "940",
                                "name": "Flamingos"
                            }
                        },
                        {
                            "id": 1397,
                            "mixID": 226,
                            "itemCode": "18403941",
                            "itemQuantity": 2,
                            "colorsId": 711,
                            "color_code": "941",
                            "color_name": "Toucans",
                            "additionalData": {},
                            "color": {
                                "id": 711,
                                "code": "941",
                                "name": "Toucans"
                            }
                        },
                        {
                            "id": 1398,
                            "mixID": 226,
                            "itemCode": "18403942",
                            "itemQuantity": 2,
                            "colorsId": 712,
                            "color_code": "942",
                            "color_name": "Hawaiian Floral",
                            "additionalData": {},
                            "color": {
                                "id": 712,
                                "code": "942",
                                "name": "Hawaiian Floral"
                            }
                        }
                    ]
                },
                "items": [],
                "images": []
            }
        },
        {
            "id": 513,
            "parentProductID": 1073,
            "variantProductID": 1119,
            "title": "Fish Mix",
            "isDefaultVariant": false,
            "status": true,
            "priority": 30,
            "timestamp": "2022-01-18T18:09:31.000Z",
            "product": {
                "id": 1119,
                "itemCode": "1840352",
                "keyword": "surfshorts-ltd-fish-mix",
                "name": "Surfshort LTD Fish Mix",
                "metaTitle": null,
                "description": "",
                "details": "",
                "image": "18403?.jpg",
                "status": true,
                "taxClassId": 0,
                "manufacturersId": 12,
                "materialsId": 0,
                "sellAs": 3,
                "upc": "093039184032",
                "defaultColor": "1031",
                "defaultCategoriesId": 18,
                "defaultCategoryKeyword": "wallets",
                "defaultParentProductsId": 1073,
                "options": "[]",
                "requireOptions": "[]",
                "canDome": false,
                "canScreenPrint": false,
                "availableForSale": true,
                "dateAvailable": "",
                "timestamp": "2022-01-18T18:09:22.000Z",
                "msrp": 13.99,
                "stdPrice": 7,
                "priceCode": "PSW",
                "stdUM": "EA",
                "salesUM": "6PK",
                "salesUMFactor": 6,
                "shipWeight": "0.0683",
                "productType": "F",
                "QuantityAvailable": 384,
                "inactiveItem": false,
                "buffer": null,
                "redirectToParent": true,
                "parentProductKeyword": "surfshorts-wallet-LTD",
                "additionalData": {
                    "size": "",
                    "subtitle": "",
                    "formatted_name": "",
                    "swatch_format": "?"
                },
                "product_season_id": 0,
                "season_code": null,
                "season_description": null,
                "season_active": null,
                "season_available": false,
                "season_teaser": null,
                "anticipatedPrice": "0.0000",
                "mix": {
                    "id": 260,
                    "productId": 1119,
                    "itemCode": "1840352",
                    "mixName": "Surfshort LTD FISH MIX",
                    "status": true,
                    "msrp": 13.99,
                    "stdPrice": 7,
                    "priceCode": "PSW",
                    "stdUM": "EA",
                    "salesUM": "6PK",
                    "salesUMFactor": 6,
                    "shipWeight": "0.0683",
                    "productType": "F",
                    "QuantityAvailable": 384,
                    "inactiveItem": 0,
                    "buffer": null,
                    "timestamp": "2022-01-18T18:08:11.000Z",
                    "items": [
                        {
                            "id": 1573,
                            "mixID": 260,
                            "itemCode": "184031021",
                            "itemQuantity": 2,
                            "colorsId": 742,
                            "color_code": "1021",
                            "color_name": "Blue Permit Fish",
                            "additionalData": {
                                "swatch_code": "",
                                "image_filename": "184031021_surfshort_LTD_permit_front.jpg",
                                "season_id": 2
                            },
                            "color": {
                                "id": 742,
                                "code": "1021",
                                "name": "Blue Permit Fish"
                            }
                        },
                        {
                            "id": 1571,
                            "mixID": 260,
                            "itemCode": "184031031",
                            "itemQuantity": 2,
                            "colorsId": 741,
                            "color_code": "1031",
                            "color_name": "Blue/Orange Bass Fish",
                            "additionalData": {
                                "swatch_code": "",
                                "image_filename": "184031031_surfshort_LTD_bass_front.jpg",
                                "season_id": 2
                            },
                            "color": {
                                "id": 741,
                                "code": "1031",
                                "name": "Blue/Orange Bass Fish"
                            }
                        },
                        {
                            "id": 1572,
                            "mixID": 260,
                            "itemCode": "18403406",
                            "itemQuantity": 2,
                            "colorsId": 139,
                            "color_code": "406",
                            "color_name": "Camo Green",
                            "additionalData": {
                                "swatch_code": "",
                                "image_filename": "18403406_surfshort_LTD_fishing_division_front.jpg",
                                "season_id": 2
                            },
                            "color": {
                                "id": 139,
                                "code": "406",
                                "name": "Camo Green"
                            }
                        }
                    ]
                },
                "items": [],
                "images": []
            }
        },
        {
            "id": 544,
            "parentProductID": 1073,
            "variantProductID": 1165,
            "title": "Tie-Dye Mix",
            "isDefaultVariant": false,
            "status": true,
            "priority": 15,
            "timestamp": "2020-11-25T23:38:12.000Z",
            "product": {
                "id": 1165,
                "itemCode": "1840304",
                "keyword": "surfshort-ltd-tiedye-mix",
                "name": "Surfshort LTD Tie-Dye Mix",
                "metaTitle": null,
                "description": "",
                "details": "",
                "image": "18403?-surfshort-tiedye-front.jpg",
                "status": true,
                "taxClassId": 0,
                "manufacturersId": 12,
                "materialsId": 0,
                "sellAs": 3,
                "upc": "093039184032",
                "defaultColor": "707",
                "defaultCategoriesId": 18,
                "defaultCategoryKeyword": "wallets",
                "defaultParentProductsId": 1073,
                "options": "[]",
                "requireOptions": "[]",
                "canDome": false,
                "canScreenPrint": false,
                "availableForSale": true,
                "dateAvailable": "",
                "timestamp": "2022-01-18T17:58:58.000Z",
                "msrp": 13.99,
                "stdPrice": 7,
                "priceCode": "PSW",
                "stdUM": "EA",
                "salesUM": "6PK",
                "salesUMFactor": 6,
                "shipWeight": "0.0683",
                "productType": "F",
                "QuantityAvailable": 120,
                "inactiveItem": false,
                "buffer": null,
                "redirectToParent": true,
                "parentProductKeyword": "surfshorts-wallet-LTD",
                "additionalData": {
                    "size": "",
                    "subtitle": "",
                    "formatted_name": "",
                    "swatch_format": "ltd-?"
                },
                "product_season_id": 0,
                "season_code": null,
                "season_description": null,
                "season_active": null,
                "season_available": false,
                "season_teaser": null,
                "anticipatedPrice": "0.0000",
                "mix": {
                    "id": 245,
                    "productId": 1165,
                    "itemCode": "1840304",
                    "mixName": "Surfshort LTD Tie-Dye Mix",
                    "status": true,
                    "msrp": 13.99,
                    "stdPrice": 7,
                    "priceCode": "PSW",
                    "stdUM": "EA",
                    "salesUM": "6PK",
                    "salesUMFactor": 6,
                    "shipWeight": "0.0683",
                    "productType": "F",
                    "QuantityAvailable": 120,
                    "inactiveItem": 0,
                    "buffer": null,
                    "timestamp": "2020-11-25T23:37:28.000Z",
                    "items": [
                        {
                            "id": 1496,
                            "mixID": 245,
                            "itemCode": "18403701",
                            "itemQuantity": 2,
                            "colorsId": 200,
                            "color_code": "701",
                            "color_name": "Rainbow Tie-Dye",
                            "additionalData": {
                                "swatch_code": "ltd-701",
                                "image_filename": "18403701-surfshort-tiedye-front.jpg",
                                "season_id": 1
                            },
                            "color": {
                                "id": 200,
                                "code": "701",
                                "name": "Rainbow Tie-Dye"
                            }
                        },
                        {
                            "id": 1497,
                            "mixID": 245,
                            "itemCode": "18403707",
                            "itemQuantity": 2,
                            "colorsId": 205,
                            "color_code": "707",
                            "color_name": "Red/White/Blue Tie-Dye",
                            "additionalData": {
                                "swatch_code": "ltd-707",
                                "image_filename": "18403707-surfshort-tiedye-front.jpg",
                                "season_id": 1
                            },
                            "color": {
                                "id": 205,
                                "code": "707",
                                "name": "Red/White/Blue Tie-Dye"
                            }
                        },
                        {
                            "id": 1495,
                            "mixID": 245,
                            "itemCode": "18403911",
                            "itemQuantity": 2,
                            "colorsId": 726,
                            "color_code": "911",
                            "color_name": "High Vis Pink/Purple",
                            "additionalData": {
                                "swatch_code": "ltd-911",
                                "image_filename": "18403911-surfshort-tiedye-front.jpg",
                                "season_id": 1
                            },
                            "color": {
                                "id": 726,
                                "code": "911",
                                "name": "High Vis Pink/Purple"
                            }
                        }
                    ]
                },
                "items": [],
                "images": []
            }
        },
        {
            "id": 567,
            "parentProductID": 1073,
            "variantProductID": 1199,
            "title": "Western Mix",
            "isDefaultVariant": false,
            "status": true,
            "priority": 40,
            "timestamp": "2022-01-18T18:02:23.000Z",
            "product": {
                "id": 1199,
                "itemCode": "1840348",
                "keyword": "surfshorts-ltd-western-mix",
                "name": "Surfshort LTD Western MIX",
                "metaTitle": null,
                "description": "",
                "details": "",
                "image": "18403?.jpg",
                "status": true,
                "taxClassId": 0,
                "manufacturersId": 12,
                "materialsId": 0,
                "sellAs": 3,
                "upc": "093039184032",
                "defaultColor": "1020",
                "defaultCategoriesId": 18,
                "defaultCategoryKeyword": "wallets",
                "defaultParentProductsId": 1073,
                "options": "[]",
                "requireOptions": "[]",
                "canDome": false,
                "canScreenPrint": false,
                "availableForSale": true,
                "dateAvailable": "",
                "timestamp": "2022-01-18T18:00:47.000Z",
                "msrp": 13.99,
                "stdPrice": 7,
                "priceCode": "PSW",
                "stdUM": "EA",
                "salesUM": "6PK",
                "salesUMFactor": 6,
                "shipWeight": "0.0683",
                "productType": "F",
                "QuantityAvailable": 438,
                "inactiveItem": false,
                "buffer": null,
                "redirectToParent": true,
                "parentProductKeyword": "surfshorts-wallet-LTD",
                "additionalData": {
                    "size": "",
                    "subtitle": "",
                    "formatted_name": "",
                    "swatch_format": "?"
                },
                "product_season_id": 0,
                "season_code": null,
                "season_description": null,
                "season_active": null,
                "season_available": false,
                "season_teaser": null,
                "anticipatedPrice": "0.0000",
                "mix": {
                    "id": 258,
                    "productId": 1199,
                    "itemCode": "1840348",
                    "mixName": "Surfshort LTD WESTERN MIX",
                    "status": true,
                    "msrp": 13.99,
                    "stdPrice": 7,
                    "priceCode": "PSW",
                    "stdUM": "EA",
                    "salesUM": "6PK",
                    "salesUMFactor": 6,
                    "shipWeight": "0.0683",
                    "productType": "F",
                    "QuantityAvailable": 438,
                    "inactiveItem": 0,
                    "buffer": null,
                    "timestamp": "2022-01-18T18:01:11.000Z",
                    "items": [
                        {
                            "id": 1565,
                            "mixID": 258,
                            "itemCode": "184031014",
                            "itemQuantity": 2,
                            "colorsId": 737,
                            "color_code": "1014",
                            "color_name": "Western Black",
                            "additionalData": {
                                "swatch_code": "",
                                "image_filename": "184031014_surfshort_LTD_western_front.jpg",
                                "season_id": 2
                            },
                            "color": {
                                "id": 737,
                                "code": "1014",
                                "name": "Western Black"
                            }
                        },
                        {
                            "id": 1566,
                            "mixID": 258,
                            "itemCode": "184031020",
                            "itemQuantity": 2,
                            "colorsId": 740,
                            "color_code": "1020",
                            "color_name": "Western White",
                            "additionalData": {
                                "swatch_code": "",
                                "image_filename": "184031020_surfshort_LTD_western_geo_front.jpg",
                                "season_id": 2
                            },
                            "color": {
                                "id": 740,
                                "code": "1020",
                                "name": "Western White"
                            }
                        },
                        {
                            "id": 1564,
                            "mixID": 258,
                            "itemCode": "18403450",
                            "itemQuantity": 2,
                            "colorsId": 168,
                            "color_code": "450",
                            "color_name": "Blue / Orange Stripe",
                            "additionalData": {
                                "swatch_code": "",
                                "image_filename": "18403450_surfshort_LTD_stripes_front.jpg",
                                "season_id": 2
                            },
                            "color": {
                                "id": 168,
                                "code": "450",
                                "name": "Blue / Orange Stripe"
                            }
                        }
                    ]
                },
                "items": [],
                "images": []
            }
        },
        {
            "id": 568,
            "parentProductID": 1073,
            "variantProductID": 1200,
            "title": "Classic Fish Mix",
            "isDefaultVariant": false,
            "status": true,
            "priority": 35,
            "timestamp": "2022-01-18T18:09:52.000Z",
            "product": {
                "id": 1200,
                "itemCode": "1840350",
                "keyword": "surfshorts-ltd-classic-fish-mix",
                "name": "Surfshort LTD Classic Fish Mix",
                "metaTitle": null,
                "description": "",
                "details": "",
                "image": "18403?.jpg",
                "status": true,
                "taxClassId": 0,
                "manufacturersId": 12,
                "materialsId": 0,
                "sellAs": 3,
                "upc": "093039184032",
                "defaultColor": "920",
                "defaultCategoriesId": 18,
                "defaultCategoryKeyword": "wallets",
                "defaultParentProductsId": 1073,
                "options": "[]",
                "requireOptions": "[]",
                "canDome": false,
                "canScreenPrint": false,
                "availableForSale": true,
                "dateAvailable": "",
                "timestamp": "2022-01-18T18:10:04.000Z",
                "msrp": 13.99,
                "stdPrice": 7,
                "priceCode": "PSW",
                "stdUM": "EA",
                "salesUM": "6PK",
                "salesUMFactor": 6,
                "shipWeight": "0.0683",
                "productType": "F",
                "QuantityAvailable": 330,
                "inactiveItem": false,
                "buffer": null,
                "redirectToParent": true,
                "parentProductKeyword": "surfshorts-wallet-LTD",
                "additionalData": {
                    "size": "",
                    "subtitle": "",
                    "formatted_name": "",
                    "swatch_format": "?"
                },
                "product_season_id": 0,
                "season_code": null,
                "season_description": null,
                "season_active": null,
                "season_available": false,
                "season_teaser": null,
                "anticipatedPrice": "0.0000",
                "mix": {
                    "id": 259,
                    "productId": 1200,
                    "itemCode": "1840350",
                    "mixName": "#Surfshort LTD FISH MIX",
                    "status": true,
                    "msrp": 13.99,
                    "stdPrice": 7,
                    "priceCode": "PSW",
                    "stdUM": "EA",
                    "salesUM": "6PK",
                    "salesUMFactor": 6,
                    "shipWeight": "0.0683",
                    "productType": "F",
                    "QuantityAvailable": 330,
                    "inactiveItem": 0,
                    "buffer": null,
                    "timestamp": "2022-01-18T18:07:21.000Z",
                    "items": [
                        {
                            "id": 1567,
                            "mixID": 259,
                            "itemCode": "18403920",
                            "itemQuantity": 2,
                            "colorsId": 704,
                            "color_code": "920",
                            "color_name": "Brook Fish",
                            "additionalData": {},
                            "color": {
                                "id": 704,
                                "code": "920",
                                "name": "Brook Fish"
                            }
                        },
                        {
                            "id": 1568,
                            "mixID": 259,
                            "itemCode": "18403921",
                            "itemQuantity": 2,
                            "colorsId": 705,
                            "color_code": "921",
                            "color_name": "Rainbow Fish",
                            "additionalData": {},
                            "color": {
                                "id": 705,
                                "code": "921",
                                "name": "Rainbow Fish"
                            }
                        },
                        {
                            "id": 1569,
                            "mixID": 259,
                            "itemCode": "18403922",
                            "itemQuantity": 2,
                            "colorsId": 706,
                            "color_code": "922",
                            "color_name": "Dark Scales",
                            "additionalData": {},
                            "color": {
                                "id": 706,
                                "code": "922",
                                "name": "Dark Scales"
                            }
                        }
                    ]
                },
                "items": [],
                "images": []
            }
        }
    ],
    "mix": null,
    "items": [],
    "images": [
        {
            "id": 339,
            "productId": 1073,
            "image": "18403701-surfshort-tiedye-back.jpg",
            "altText": "#18403701",
            "priority": 0,
            "status": 1,
            "timestamp": "2020-11-25T23:40:22.000Z"
        },
        {
            "id": 243,
            "productId": 1073,
            "image": "18403351-Surfshort-Wallet-RealTree-Edge-Back.jpg",
            "altText": "#18403351",
            "priority": 10,
            "status": 1,
            "timestamp": "2020-03-04T21:12:48.000Z"
        },
        {
            "id": 244,
            "productId": 1073,
            "image": "18403352-Surfshort-Wallet-RealTree-Wave-Back.jpg",
            "altText": "#18403352",
            "priority": 20,
            "status": 1,
            "timestamp": "2020-03-04T21:12:43.000Z"
        },
        {
            "id": 245,
            "productId": 1073,
            "image": "18403809-Surfshort-Wallet-USA-Flag-Back.jpg",
            "altText": "#18403809",
            "priority": 30,
            "status": 1,
            "timestamp": "2020-03-04T21:13:31.000Z"
        },
        {
            "id": 246,
            "productId": 1073,
            "image": "18403920-Surfshort-Wallet-Brook-Fishes-Back.jpg",
            "altText": "#18403920",
            "priority": 40,
            "status": 1,
            "timestamp": "2020-03-04T21:14:06.000Z"
        },
        {
            "id": 247,
            "productId": 1073,
            "image": "18403921-Surfshort-Wallet-Rainbow-Fish-Back.jpg",
            "altText": "#18403921",
            "priority": 50,
            "status": 1,
            "timestamp": "2020-03-04T21:14:38.000Z"
        },
        {
            "id": 248,
            "productId": 1073,
            "image": "18403922-Surfshort-Wallet-Fish-Scales-Back.jpg",
            "altText": "#18403922",
            "priority": 60,
            "status": 1,
            "timestamp": "2020-03-04T21:15:01.000Z"
        },
        {
            "id": 249,
            "productId": 1073,
            "image": "18403940-Surfshort-Wallet-Flamingos-Back.jpg",
            "altText": "#18403940",
            "priority": 70,
            "status": 1,
            "timestamp": "2020-03-04T21:15:33.000Z"
        },
        {
            "id": 250,
            "productId": 1073,
            "image": "18403941-Surfshort-Wallet-Toucans-Front.jpg",
            "altText": "#18403941",
            "priority": 80,
            "status": 1,
            "timestamp": "2020-03-04T21:16:00.000Z"
        },
        {
            "id": 251,
            "productId": 1073,
            "image": "18403942-Surfshort-Wallet-Hawaiian-Floral-Back.jpg",
            "altText": "#18403942",
            "priority": 90,
            "status": 1,
            "timestamp": "2020-03-04T21:16:27.000Z"
        },
        {
            "id": 337,
            "productId": 1073,
            "image": "18403911-surfshort-tiedye-back.jpg",
            "altText": "#18403911",
            "priority": 100,
            "status": 1,
            "timestamp": "2020-11-25T23:39:43.000Z"
        },
        {
            "id": 338,
            "productId": 1073,
            "image": "18403707-surfshort-tiedye-back.jpg",
            "altText": "#18403707",
            "priority": 105,
            "status": 1,
            "timestamp": "2020-11-25T23:40:05.000Z"
        },
        {
            "id": 362,
            "productId": 1073,
            "image": "184031014_surfshort_LTD_western_back.jpg",
            "altText": "#184031014",
            "priority": 110,
            "status": 1,
            "timestamp": "2021-11-01T20:58:51.000Z"
        },
        {
            "id": 363,
            "productId": 1073,
            "image": "184031020_surfshort_LTD_western_geo_back.jpg",
            "altText": "#184031020",
            "priority": 115,
            "status": 1,
            "timestamp": "2021-11-01T20:57:12.000Z"
        },
        {
            "id": 364,
            "productId": 1073,
            "image": "184031021_surfshort_LTD_permit_back.jpg",
            "altText": "#184031021",
            "priority": 120,
            "status": 1,
            "timestamp": "2021-11-01T20:58:05.000Z"
        },
        {
            "id": 365,
            "productId": 1073,
            "image": "184031031_surfshort_LTD_bass_back.jpg",
            "altText": "#184031031",
            "priority": 125,
            "status": 1,
            "timestamp": "2021-11-01T20:59:53.000Z"
        },
        {
            "id": 366,
            "productId": 1073,
            "image": "18403406_surfshort_LTD_fishing_division_back.jpg",
            "altText": "#18403406",
            "priority": 130,
            "status": 1,
            "timestamp": "2021-11-01T21:00:55.000Z"
        },
        {
            "id": 367,
            "productId": 1073,
            "image": "18403450_surfshort_LTD_stripes_back.jpg",
            "altText": "#18403450",
            "priority": 135,
            "status": 1,
            "timestamp": "2021-11-01T21:02:02.000Z"
        }
    ]
}
